# Generated by Django 4.2.9 on 2024-02-06 11:30
"""
    Module name :- 0002_delete_department
"""

from django.db import migrations


class Migration(migrations.Migration):
    """
    Migrations
    """

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Department",
        ),
    ]
