# Generated by Django 4.2.9 on 2024-02-06 11:37
"""
    Module name :- 0003_equipment_assigned
"""

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Migration
    """

    dependencies = [
        ("store", "0002_delete_department"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipment",
            name="assigned",
            field=models.BooleanField(default=False),
        ),
    ]
