# Generated by Django 4.2.9 on 2024-02-08 06:24
"""
    Module name :- 0004_remove_equipment_assigned_allocation_..
"""

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    """
    Migration
    """

    dependencies = [
        ("store", "0003_equipment_assigned"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="equipment",
            name="assigned",
        ),
        migrations.AddField(
            model_name="allocation",
            name="returned",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="allocation",
            name="equipment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="allocation",
                to="store.equipment",
            ),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="buy_date",
            field=models.DateField(),
        ),
    ]
